### ISSUE TITLE
Unable to bookmark

### ISSUE THREAD

**Issue by raynux** [sgwilym/wikimania#2] opened 2015-09-10 04:12 UTC
Clicking on a star (assuming it is for bookmarking) results ...

<img width="1420" alt="screen shot 2015-09-10 at 13 11 06" src="https://cloud.githubusercontent.com/assets/203797/9779973/6a799490-57bd-11e5-8d50-40dc843e430d.png">

**Comment by sgwilym** [comment] 2015-09-10 10:48
Thanks, looks like another problem caused by the app expecting an array when there wasn’t one, caused by me not testing from a completely blank slate. Fixed with https://github.com/sgwilym/wikimania/commit/75a5428f7a2e602e415883e21bb446f2f58f2ae1.

**Closed by sgwilym** 2015-09-10 10:48 UTC
